
# Twitch
TwitchVoice = twitch

TwitchGame = Lineage II Imperium

TwitchServer = Lineage II Imperium

#fwkef293gk23g23gs token
TwitchToken = 

TwitchMinStream = 60
TwitchRewardEvery = 60
TwitchMinViewer = 6393,10